### ISSUE TITLE
Virtual Paths

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#169] opened 2020-04-12 20:20 UTC
## Summary

What: Implement virtual paths.

Why: It would be nice to mount `/dir` to `/some/other/dir` for filesystem flexibility. For example, if I started `/src/app.ts` with a static path of `/public`, I would have to define `/public` as `../public`. It would be nice to define it as `/public` instead.

## Acceptance Criteria

- [ ] Virtual paths can be mounted to static paths
- [ ] Tests
- [ ] Documentation

## Example Pseudo Code (for implementation)

```typescript
new Drash.Http.Server({
  static_paths: ["/public"],
  static_paths_mounting: {
    "/public": `../public`
  }
});
```

**Comment by ebebbington** [comment] 2020-05-30 01:58
Wonder if the following might be better? Only scenario i can think of where it wouldnt be is if a dev  has no need to mount a static path

```
new Drash.Http.Server({
    static_paths: [
        { "/public": "../public},
        { "/img": "../public/img }
    ]
});
```

Just feel along with the `static_paths`, the `static_paths_mounting` might be a bit uneccesary? Though i get it probably adds more customisation, and my approach above means you have to add a mount **for each path** - might be a crappy approach then

**Comment by crookse** [comment] 2020-05-30 02:03
Yea idk how i feel about the mount for each path. Seems to bloat the code even if the user doesn't want to add mount paths.

**Comment by Guergeiro** [comment] 2020-05-30 10:30
I don't know what this adds to be honest. We could do just for the sake of doing it but, in my opinion, is a feature is not required and just gives us one more thing to maintain. 

For example, if I was a developer, I would most likely use a symlink to the directory. This is something that exists at OS level, in every OS. Using the example, if I wanted `/dir` to also represent `/some/other/dir` I would just `ln -s /dir /some/other/dir`.

If I'm not understanding correctly, please enlighten me then 😅

**Comment by crookse** [comment] 2020-05-30 10:52
It gives you more control over how your filesystem is structured and secured and prevents users from understanding your filesystem. Say you have the following filesystem structure:

```
|- var/
   |- www/
      |- public/
      |- app.ts
```

You would serve your app like this:

```
new Drash.Http.Server({
  directory: "/var/www",
  static_paths: ["/public"],
});
```

A request to `yourdomain.com/public` would map to `/var/www/public`. If you don't want user's to know that `/public` is served from your project's root directory, then you would need a way to map `/public` virtually. Let's say you wanted this filesystem structure instead:

```
|- var/
   |- www/
      |- app.ts
   |- www_public/
```

As of right now you won't be able to serve this kind of filesystem structure because it would look like:

```
new Drash.Http.Server({
  directory: "/var/www",
  static_paths: ["../www_public"],
});
```

Also, you wouldn't be able to serve `/public` now. You would have to serve `../www_public`, which would be weird from a URL (e.g., `yourdomain.com/../www_public`). I don't even think that would work. This also shows users how your filesystem is structured. In order to serve `/public`, you would need to have some mechanism like the following:

```
new Drash.Http.Server({
  directory: "/var/www",
  static_paths: ["../www_public"],
  static_paths_mounting: {
    "../www_public": "/public"
  }
});
```

Now you can serve `/public` and URLs would look like `yourdomain.com/public`. From a security standpoint, this shows users that `/public` starts at the root of your project directory, but in reality it doesn't because it's virtually mounted. From a flexibility standpoint, this allows you to move your directories freely and add different permissions to them separate from the application's directory.

**Comment by Guergeiro** [comment] 2020-05-30 11:06
I see what you mean. Though this almost feels like it should be handled in the Apache/NGINX configuration. 

Let me try to understand, you want to serve static files from `/public`. The problem is that when you access the website it is served under `youdomain.com/public`?

**Comment by crookse** [comment] 2020-05-30 11:10
Yea. And what if you don’t want to serve / instead of /public? That means users will have access to your projects root directory and can read your src files. Because they could go to yourdomain.com/src/sometime.ts since you’ve allowed / to be public as a static path

**Comment by Guergeiro** [comment] 2020-05-30 11:28
Okay, I understand now. Though I think we might be overcomplicating the things. I don't know the best way to solve this. In my opinion, we should solve this by also passing some kind of url.

```typescript
new Drash.Http.Server({
  directory: "/var/www",
  static_paths: [
    {
      "/": "/public1",
    },
    {
      "/img": "/public2"
    }
  ]
});
```

This would map:
- `yourdomain.com` => `/public1`
- `yourdomain.com/img` => `/public2`

**Comment by crookse** [comment] 2020-05-30 11:29
So are you saying we should just default to having virtual paths as Ed said?

**Comment by Guergeiro** [comment] 2020-05-30 11:34
Yes. ExpressJS/KOA also does like that (and I use a lot of ExpressJS/KOA in Node). I believe it's the best option honestly...

**Comment by crookse** [comment] 2020-05-30 11:35
Ok well if it's known by the JS community then yea we shouldn't really worry about it too much and just implement it the way people are used to

**Comment by crookse** [comment] 2020-05-30 11:39
To make sure we're backwards compatible, we need to implement the following syntax:

```
new Drash.Http.Server({
  directory: "/var/www",
  static_paths: [
    {"/": "/public },
    "/something-else",
  ]
});
```

When we parse if a request is for a static path, then we'll check to see if they match either a string in the array or an object's value. Thoughts?

**Comment by Guergeiro** [comment] 2020-05-30 11:46
In my  opinion, when we pass only the object, it should default to `/`.

```typescript
new Drash.Http.Server({
  directory: "/var/www",
  static_paths: ["/public"]
});
```

This would map:
- `yourdomain.com` => `/public`

**Comment by ebebbington** [comment] 2020-05-30 12:28
> I see what you mean. Though this almost feels like it should be handled in the Apache/NGINX configuration.
> 
> Let me try to understand, you want to serve static files from `/public`. The problem is that when you access the website it is served under `youdomain.com/public`?

As we've seen though, you don't even need to use Apache or Nginx with Drash

**Comment by ebebbington** [comment] 2020-10-05 23:08
Why don't we go with:
```
static_paths: {
   "/js": "./public/js",
  ...
}
```
And if one doesn't need to be mounted, they could just do:
```
static paths: {
  "/js": "/js"
}
```
And i don't think there would need to be any extra code to account for this

BUT it'd be a breaking change

**Comment by crookse** [comment] 2020-10-06 00:12
i don't think it'd be a breaking change because we can be backwards compatible right?

**Comment by ebebbington** [comment] 2020-10-06 00:14
Cause the type assigned to `Server#static_paths` would change right? so doing `static_paths = ["..."]` would throw a TSC error? maybe i'm getting stuff muddled up tho

**Comment by crookse** [comment] 2020-10-06 00:26
my thinking is (and @Guergeiro might disagree) we can keep it as an array and parse if an array element is an object. if it is then we assume the key is the virtual path and the value is the source directory.

or we could just append a type to the current typings? {current typing} | {new typing}

**Comment by ebebbington** [comment] 2020-10-06 00:31
yeah tbh i personally think that will be the best best:

* we arent adding an extra config prop (won't be bloated)
* we can still allow users to switch (or transition) between the two easily (there's a word for this but can't remember it)

and like you say, it'd just be:
```typescript
private static_paths: Array<string> | {[key: string]: string}

if (Array.isArray(this.static_paths) {
   ...
} else {
   ...
}
```

**Comment by Guergeiro** [comment] 2020-10-06 11:53
I agree with this. Should be fine 😄

**Closed** 2020-10-30 22:54 UTC
Labels: enhancement
